### ISSUE TITLE
Limit to 100 images

### ISSUE THREAD

**Issue by dbedrenko** [pipoket/booru-grabber#1]
The booru API seems to limit the number of images downloaded to only 100. Did this limit exist before you decided to use the API? Can we bypass this limit?

**Comment by pipoket** [comment]
Yes, the limit did exist from the very beginning, since when I first knew the existence of API. And AFAIK there is nothing user can control about it, I think it would be impossible for developer to bypass the limit.

**Comment by dbedrenko** [comment]
Hmm after making this bug report I found 2 other programs, and they seem to download more than 100 images at a time:

https://github.com/Bionus/imgbrd-grabber
http://hydrusnetwork.github.io/hydrus/

I think it's possible if you do the scraping yourself rather than use the API, but it's a lot more work.

**Comment by pipoket** [comment]
As of now(Oct, 2015), API is down, so no other way than scraping data by myself anyway :3
Anyway, closing the issue.
