### ISSUE TITLE
Error: unknown url type:

### ISSUE THREAD

**Issue by Litoba** [pipoket/booru-grabber#6]
![_2017_02_09_06_36_34_800](https://cloud.githubusercontent.com/assets/15212715/22758463/302285f0-ee92-11e6-8ae0-020a8ac98d7b.png)
Hello, pipoket.
sorry, I am bad at English.
Recently, grabber can't download by this error.
when you get a moment, could you check this problem?

**Comment by the612toon** [comment]
I really hope the developer fixes this. :(

**Comment by pipoket** [comment]
OK. This seems huge. Let me take a look at it.

**Comment by pipoket** [comment]
As Gelbooru started to fully support HTTPS connection, they removed URL scheme(http/https) from their original image href link which is a totally legit and good update.

A new updated release which handles this correctly will be uploaded soon.
